### ISSUE TITLE
qBitTorrent: Tracker not working - Unreachable

### ISSUE THREAD

**Issue by cubuzz** [naim94a/udpt#114]
Heya!
Tried setting this up for private purposes, however qBitTorrent fails to connect to my server with "Unreachable". I can interact with the REST API just fine, and other UDP trackers work well.

I've tried digging into this issue and my server reports that it receives the client package announcing the torrent, however the server is not sending a reply back. I can rule out the possibility of firewall here because I was able to replicate this issue in a DMZ setup.

Any ideas? I haven't tried the last release yet, only built myself.

**Comment by Endleon201** [comment]
I have this same issue, so maybe, creator, take a look into this?

**Comment by TomasKralCZ** [comment]
Not sure if it's the same problem, but there seems to be an issue with message serialization
https://github.com/naim94a/udpt/blob/f6e94a3da1f33e7b9d6a6fcfc42a8573f5884400/src/server.rs#L47-L54

I don't have much experience with bincode, but I was able to contact this tracker from qBittorrent after adding the `.with_fixint_encoding()` option.

**Comment by naim94a** [comment]
Sorry for the delay on checking this issue. 
Thank you very much to @TomasKralCZ for pointing out the bug! 
Should be fixed in the latest release.
