### ISSUE TITLE
config ok but udpt refuse to start

### ISSUE THREAD

**Issue by olemaire** [naim94a/udpt#17]
Hi,

I face the following issue when trying to start udpt (-i -c <myconfigfile>):

> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast>>'
>   what():  boost::bad_any_cast: failed conversion using boost::any_cast
> Aborted

The config file seems ok:
./udpt -t -c tracker.conf 
Config OK

What should I look for to fix?

TIA for any answer!

Cheers,
-- 
lem

**Comment by naim94a** [comment]
Hi @olemaire,
Attaching the tracker.conf that you used would be very helpful. 
Would you mind to attach it?

**Comment by olemaire** [comment]
Hi!

sure, no pb - hereafter:
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[db]
driver=sqliste3
param=/mnt/dcpbank/tracker/build/udpt/tracker.db
#param=:memory:

[tracker]
is_dynamic=1
port=6969
threads=5
allow_remotes=1
allow_iana_ips=0
announce_interval=60
cleanup_interval=120

[apiserver]
enable=1
threads=1
port=6969

[logging]
#filename=./tracker.log
filename=/mnt/dcpbank/tracker/build/udpt/tracker.log
level=debug

[daemon]
#chdir=/mnt/dcpbank/tracker/build/udpt/

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Cheers,
— 
lem

**Comment by naim94a** [comment]
should work now! (please confirm fix)

**Comment by olemaire** [comment]
I confirm: working now. 
MTHX!

Cheers,
-- 
lem
