### ISSUE TITLE
no logs?

### ISSUE THREAD

**Issue by olemaire** [naim94a/udpt#19]
Hi!,

udpt ran as daemon or interactively seems to ignore my logging configuration:
* does not create a log file
* does not report debug infos - even if asked so by configuration file.

Here is my configuration file regarding logging:

> [logging]
> #filename=/mnt/dcpbank/tracker/build/udpt/tracker.log
> filename=/tmp/tracker.log
> level=debug

And here is the starting of udpt in interactive mode (interrupted after some time by CTRL+C:

```
blowjog@blowjog:/mnt/dcpbank/tracker/build/udpt$ ./udpt -i -c tracker.conf 
1454351720: (I): Starting maintenance thread (1/6)
1454351720: (I): Starting thread (2/6)
1454351720: (I): Starting thread (3/6)
1454351720: (I): Starting thread (4/6)
1454351720: (I): Starting thread (5/6)
1454351720: (I): Starting thread (6/6)

1 Clients Dumped.
E:(null)
1 Clients Dumped.
E:(null)
^C

```

What did I miss?

**Comment by naim94a** [comment]
This issue will be resolved by Milestone "Version 2" (issue #14).
