### ISSUE TITLE
make all fails

### ISSUE THREAD

**Issue by tmberg** [naim94a/udpt#24]
root@ns1:/tmp/udpt# make all
g++ -c -o main.o src/main.cpp
g++ -c -o udpTracker.o src/udpTracker.cpp
g++ -c -o database.o src/db/database.cpp
g++ -c -o driver_sqlite.o src/db/driver_sqlite.cpp
g++ -c -o settings.o src/settings.cpp
cc -c -o tools.o src/tools.c
g++ -c -o httpserver.o src/http/httpserver.cpp
g++ -c -o webapp.o src/http/webapp.cpp
g++ -c -o logging.o src/logging.cpp
Linking...
g++ -O3 -o udpt main.o udpTracker.o database.o driver_sqlite.o settings.o tools.o httpserver.o webapp.o logging.o  -lsqlite3
/usr/bin/ld: udpTracker.o: undefined reference to symbol 'pthread_cancel@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:36: recipe for target 'udpt' failed
make: *** [udpt] Error 1

**Comment by naim94a** [comment]
Hi @tmberg,
The output of that you provided seems outdated, (ex. there are missing flags from the current Makefile).
Please update to the current master.

**Comment by tmberg** [comment]
Hm.. Ok. Got it from here: https://github.com/naim94a/udpt/wiki/BuildLinux

**Comment by naim94a** [comment]
Sorry about that,
Part of the wiki was recently imported from the old google-code site, and is outdated.
Seems like you cloned the code from google-code, and not from GitHub.
