### ISSUE TITLE
A problem in Dietpi

### ISSUE THREAD

**Issue by ripoyet** [naim94a/udpt#27]
Hi. Thanks for your software. I'm a little new in Linux. I've installed udpt in my Odroid C2 with Dietpi. Linux show me one problem that I don't know to resolve. This is the problem:

```
g++ -g -std=gnu++11 -c -o main.o src/main.cpp -DBOOST_LOG_DYN_LINK
src/main.cpp:27:37: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
                                     ^
compilation terminated.
Makefile:28: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

If you could show me the way, I'll thankful.
Thanks in advance.

**Comment by ripoyet** [comment]
Hi, I've solved the problem and I've installed all ok. But now, I can't enter in the tracker. I'm writting MyIP:6969 and it don't enter in the udp tracker. If you could help me, it could be greatfull.
This is the command that I've wrote to solve the first problem:
`sudo apt-get install gcc g++ make libsqlite3-dev git cmake libboost-date-time-dev libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-serialization-dev libboost-thread-dev libboost-log-dev subversion zlib1g-dev`
Thanks in advance.

**Comment by naim94a** [comment]
Where did you write MyIp:6969? The port is a UDP port, not TCP/HTTP - not accessible from your browser.
Adding "udp://MyIp:6969" to  the tracker list of a torrent should work.
