### ISSUE TITLE
How to configure API server to listen to IP other than 127.0.0.1? (to make it listen on all interfaces)

### ISSUE THREAD

**Issue by pataquets** [naim94a/udpt#36]
I'm almost done on adding Docker workflow to udpt hacking alternatives.
To allow any udpt port to be contacted outside a Docker container, it should be able to listen to 0.0.0.0. The exposed iface and ports are meant to be configured outside the container with standard port mappings. API server port can be configured, but I could not find a way to change the listen iface, neither inside udpt.conf or via the command line (did an --all-help and no clue).
Is it possible?
TIA.

**Comment by naim94a** [comment]
This issue was solved & merged to master
