### ISSUE TITLE
Create 'official' Docker image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [naim94a/udpt#39]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, documentation could easily include a canonical `docker run` statement to quickly spin up a udpt instance with just a single command.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays AB when listing images (mine is shown):
```
$ docker search udpt
NAME                      DESCRIPTION     STARS     OFFICIAL   AUTOMATED
pataquets/udpt               udpt                                      0                    [OK]
[...]
pataquets/udpt-src           udpt build from source                    0                    [OK]
```
Just a free Docker Hub account and a quick setup would do. Ping me if you need help.
See also #38.

**Comment by naim94a** [comment]
Hi @pataquets; 
Sorry for the long delay...
Done, can be found @ https://hub.docker.com/r/naim94a/udpt

**Comment by pataquets** [comment]
Awesome! Thank you.
Sent a separate PR to add this to docs.
