### ISSUE TITLE
CMake build failure on Debian

### ISSUE THREAD

**Issue by m-flak** [naim94a/udpt#40]
**Linux 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 GNU/Linux, DEBIAN FLAVOUR, is no buildie...**
> ``CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GTEST
    linked by target "udpt_tests" in directory /home/malexa/src/udpt
LIBEVENT
    linked by target "udpt" in directory /home/malexa/src/udpt
    linked by target "udpt_tests" in directory /home/malexa/src/udpt
LIBEVENTP
    linked by target "udpt" in directory /home/malexa/src/udpt
    linked by target "udpt_tests" in directory /home/malexa/src/udpt
SQLITE
    linked by target "udpt" in directory /home/malexa/src/udpt
    linked by target "udpt_tests" in directory /home/malexa/src/udpt``

I have checked my dependencies already bruh...

**Comment by naim94a** [comment]
I can't seem to reproduce the problem in a chroot environment.
It seems that the following packages are not installed on your machine:
* libgtest-dev
* libevent-dev
* libsqlite3-dev

**Comment by m-flak** [comment]
You don't say... 😐 I could have sworn that I had already done-and-able
installed those. Thanks.
