### ISSUE TITLE
API Examples not Working

### ISSUE THREAD

**Issue by cr0bar** [naim94a/udpt#43]
Hi,

I'm trying to use the API examples but keep getting the following error when adding a hash:

`curl "http://127.0.0.1:1338/api?action=add&hash=**********************************"`

returns:

`<H2>Not Found</H2>`

My udpt.conf file is as follows:

```
[db]
driver=sqlite3
param=/home/udpt/udpt/udpt.db

[tracker]
is_dynamic=no
port=1337
threads=5
allow_remotes=yes
allow_iana_ips=no
announce_interval=1800
cleanup_interval=120

[apiserver]
enable=yes
iface=127.0.0.1
port=1338

[logging]
filename=udpt-log.log
level=info
```

Any advice would be appreciated.

**Comment by naim94a** [comment]
Hi @cr0bar,
Thank you for reporting this issue. 
It seems that the documentation is not up to date.

Please try using:
`curl -X POST "http://127.0.0.1:1338/api/torrents?action=add&info_hash=*****"`
for adding, or
`curl -X DELETE "http://127.0.0.1:1338/api/torrents?action=remove&info_hash=******"`
for removing.

**Comment by cr0bar** [comment]
That's great thanks, seems like 'remove' is working fine, but 'add' is returning an error:

```
curl -X POST "http://127.0.0.1:1338/api/torrents?action=add&info_hash=**********************************"
{"error": "Failed to add torrent."}
```

```
curl -X DELETE "http://127.0.0.1:1338/api/torrents?action=remove&info_hash=**********************************"
{"result": "Okay"}
```

**Comment by naim94a** [comment]
The cause is probably the database's permissions. Does `udpt` have permissions to write to the database?

**Comment by cr0bar** [comment]
I've just deleted the database file and restarted udpt and it's working now. It did have udpt set as the owner and write access so not sure what happened. but it's working now.

Thanks for the support.
