### ISSUE TITLE
info_hash not registered

### ISSUE THREAD

**Issue by cr0bar** [naim94a/udpt#44]
Following on from issue 43, I'm now receiving the following problem.

The API call returns Okay:

```
curl -X POST "http://127.0.0.1:1338/api/torrents?action=add&info_hash=**********************************"
{"result": "Okay"}
```

..and I can see a new table starting 't' followed by a hash value (not the same as the info_hash provided) and a new row in 'torrents' with a blob containing the same value as the newly created 't' table, however uTorrent returns 'info_hash not registered.'.

**Comment by cr0bar** [comment]
hash in uTorrent

`40f5d57b94e3bc20ff972d918d67e385868bdf05`

info_hash in torrent

```
0005050b04030c000f070d010d070305
060b0f05

```
table name

`t0005050b04030c000f070d010d070305060b0f05`

**Comment by naim94a** [comment]
Should be fixed now, please reopen if it isn't.
