### ISSUE TITLE
Annouce responce not show the ammount of seeders and leechers

### ISSUE THREAD

**Issue by VictorGerin** [naim94a/udpt#46]
As can seed by this wireshark dump

the result has some endpoint list but not return the amount os seeders and leechers

Obs: this dump is the announce response.

00:00:00:01:00:00:04:bc:00:00:00:0a:00:00:00:00:00:00:00:00:c0:a8:00:0f:bd:00:c0:a8:00:0f:a1:5e:c0:a8:00:0f:93:8a:c0:a8:00:0f:ba:92:c0:a8:00:0f:ce:a7:c0:a8:00:0f:c0:d0:c0:a8:00:0f:e7:d4:c0:a8:00:0f:b0:ef:c0:a8:00:0f:98:f5:c0:a8:00:0f:86:fa

here i have break to seed better

00:00:00:01 <- action
00:00:04:bc <- transaction_id
00:00:00:0a <- update interval
00:00:00:00 <- leechers
00:00:00:00 <- seeders

endpoint list
c0:a8:00:0f:bd:00
c0:a8:00:0f:a1:5e
c0:a8:00:0f:93:8a
c0:a8:00:0f:ba:92
c0:a8:00:0f:ce:a7
c0:a8:00:0f:c0:d0
c0:a8:00:0f:e7:d4
c0:a8:00:0f:b0:ef
c0:a8:00:0f:98:f5
c0:a8:00:0f:86:fa

**Comment by naim94a** [comment]
Peer statistics are updated at a specified interval (when cleanup runs). By default this happens every 2 minutes.

**Comment by VictorGerin** [comment]
But i have reduce the cleanup time to one second

**Comment by naim94a** [comment]
This should be fixed now, please reopen if it's not fixed.
