### ISSUE TITLE
Error string "thin"

### ISSUE THREAD

**Issue by ripoyet** [naim94a/udpt#49]
Hello naim94a. I've done what you tell in readme:
git clone https://github.com/naim94a/udpt.git
cd udpt
cargo build --release

The last step give me this error:
error: failed to parse manifest at `/home/ripoyet/install/udpt/Cargo.toml`

Caused by:
  invalid type: string "thin", expected a boolean for key `profile.release.lto`

Please, help me. Thanks.

**Comment by naim94a** [comment]
You're probably using an older version of rust. The current stable rust supports thin lto.

Updating your compiler should solve the problem, otherwise you can set the flag to true, it should work too.
