### ISSUE TITLE
Can't kill the server with keyboard shortcut

### ISSUE THREAD

**Issue by MuhiaKevin** [naim94a/udpt#55]
`ctrl-c` doesn't kill the server. This is the output:

`➜  Downloads ./udpt-rs -c udpt.toml
1590073778[udpt_rs][INFO]	logging initialized.
1590073778[actix_net::server::server][INFO]	Starting 4 workers
1590073778[actix_net::server::server][INFO]	Starting server on 192.168.1.149:1200
^C1590073780[actix_net::server::server][INFO]	SIGINT received, exiting
1590073780[actix_net::server::worker][INFO]	Shutting down worker, 0 connections
1590073780[actix_net::server::worker][INFO]	Shutting down worker, 0 connections
1590073780[actix_net::server::worker][INFO]	Shutting down worker, 0 connections
1590073780[actix_net::server::worker][INFO]	Shutting down worker, 0 connections
^C1590073780[actix_net::server::server][INFO]	SIGINT received, exiting
`

Then it just hangs...

Am using Xubuntu linux 18.04.

**Comment by naim94a** [comment]
According to the logs, the version of udpt is outdated. This should work in the latest version
