### ISSUE TITLE
trouble with build

### ISSUE THREAD

**Issue by xeroiv** [naim94a/udpt#56]
I am having trouble with the build on the latest version.  When I try to execute cargo build --release it complains at me on Debian 10.

```
cargo build --release
error: failed to parse lock file at: /root/udpt/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

**Comment by naim94a** [comment]
What rust & cargo version are you using? 
My guess is the versions Debian's repositories use are outdated...

As a workaround try deleting Cargo.lock
