### ISSUE TITLE
API - Access Denied

### ISSUE THREAD

**Issue by zmmmspy** [naim94a/udpt#57]
Is there an API curl example for how to pass the authorization token?

**Comment by naim94a** [comment]
I should probably add an example to the documentation...

1. Add a token to your configuration & restart the tracker:
```toml
[http]
bind_address = "127.0.0.1:1212"

[http.access_token]
someone = "MyAccessToken"
```

2. Add (if not in dynamic mode), flag or unflag a torrent:
```bash
# Unflag or Add a torrent
curl -X POST http://127.0.0.1:1212/t/1234567890123456789012345678901234567890?token=MyAccessToken -d "{\"is_flagged\": false}" -H "Content-Type: application/json"

# Flag a Torrent
curl -X POST http://127.0.0.1:1212/t/1234567890123456789012345678901234567890?token=MyAccessToken -d "{\"is_flagged\": true}" -H "Content-Type: application/json"
```

Note: Torrents without peers will be removed automatically.

3. List registered torrents
```bash
curl http://127.0.0.1:1212/t/?token=MyAccessToken

# Get details about specific torrents
curl  http://127.0.0.1:1212/t/1234567890123456789012345678901234567890?token=MyAccessToken
```

**Comment by zmmmspy** [comment]
That works! However, from testing I can ONLY run the curl from 127.0.0.1. I can get to http on the 10.0.0.0/8 network but anytime you try to pull data/curl you receive Access Denied.

bind_address does not seem to do anything. I tested 0.0.0.0.

Thank you!

**Comment by naim94a** [comment]
Glad to hear that it works!

The bind address will change the interface the server is bound to. I realize that If you'd bind to 192.168.1.1 for example - you wouldn't be able to access the API at the application level, therefore I've removed the check in commit 92ae9e7954e8c36358cb8ac519cb5d7305be05fc.

**Comment by zmmmspy** [comment]
Confirmed working! Thank you!! 👍  :)

--Side info from rebuild--
warning: unused variable: `addr`
  --> src/webserver.rs:90:33
   |
90 |                     if let Some(addr) = peer_addr {
   |                                 ^^^^ help: consider prefixing with an underscore: `_addr`
   |
   = note: `#[warn(unused_variables)]` on by default

    Building [=====================================================> ] 138/139: udpt-rs(bin)


    Finished release [optimized] target(s) in 59.11s
-------------------------------


Very happy to see you're active and willing to help! Thank you again!
