### ISSUE TITLE
Windows Service or Linux/Unix daemon

### ISSUE THREAD

**Issue by shirshak55** [naim94a/udpt#74]
I would like to work on these part if nobody has started it? 

Thanks.

**Comment by naim94a** [comment]
Hi @shirshak55! 
If you're interested, nobody is working on this AFAIK

**Comment by shirshak55** [comment]
thanks I shall work on windows daemon part as I do have some little experience :D

**Comment by kmmndr** [comment]
Hi all :-)

I think this is more a packager task as it depends of the platform. But you may want to add examples into a contrib folder.

Udpt is now available as an [AlpineLinux package](https://git.alpinelinux.org/aports/tree/testing/udpt?id=c4736f1fadd48b09870918f3d1077e65d81890cc) :tada: 
This can be an example of service for [OpenRC](https://wiki.gentoo.org/wiki/Project:OpenRC) (the init system used by AlpineLinux)
[https://git.alpinelinux.org/aports/tree/testing/udpt/udpt.initd](https://git.alpinelinux.org/aports/tree/testing/udpt/udpt.initd?id=c4736f1fadd48b09870918f3d1077e65d81890cc)

**Comment by shirshak55** [comment]
sorry, I forgot to notify but in windows, I think we can just use nssm and it should work fine. 

Closing this :)
